server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: service-request
          uri: lb://service-request
          predicates:
            - Path=/services/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka

